server:
  port: ":8080"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "123456"
  name: "m_ai"
  sslmode: "disable"

auth:
  secret_key: "secret_key"
  salt: "secret_salt"
